services:
  postgres:
    image: postgres:15
    container_name: contact_postgres
    restart: unless-stopped
    env_file: 
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - contact-dev-data:/var/lib/postgresql/data

  contact-service:
    container_name: contact_service
    build: .
    restart: unless-stopped
    env_file:
      - service.env
    ports:
      - "8089:8080"

volumes:
  contact-dev-data: